### ISSUE TITLE
New command for getting the IP address.

### ISSUE THREAD

**Issue by zkanda** [codekitchen/dinghy#11]
Hi in boot2docker there's an easy command on getting the IP address of the virtualmachine, I think it would be helpful to add it here:
```
dinghy ip
```

**Comment by codekitchen** [comment]
agreed -- right now the IP is actually hard-coded and static, but that eventually needs to change since it could conflict with another virtual interface already on the user's computer.

I added a `dinghy ip` command in https://github.com/codekitchen/dinghy/commit/679d31478d251c860c6b5f074cca207812bf8c7d that just returns the static IP for now.
