### ISSUE TITLE
Windows support via winnfsd?

### ISSUE THREAD

**Issue by fballiano** [codekitchen/dinghy#112]
Hello everybody and thanks for the great work on dinghy, it works really well and it should be the defaut on OSX.

A couple of things that I'm wondering are about:
- kitematic support (already covered in #96) but probably it's more likely a kitematic issue
- windows support for sharing the Dockerfiles/images with windows developers (for what I'm doing I've to "usermod" some processes in my images to match the shared files owner but this makes my images not compatible with the default docker-machine thus also with windows devs)

Is it a completely out-of-the-world idea to make dinghy work on windows via winnfsd? I stumbled upon this project and it seems to me (but at the moment I really have just a little experience with the docker ecosystem) that it could be used for dinghy too:
https://github.com/winnfsd/vagrant-winnfsd

Thanks for your great work!

**Comment by codekitchen** [comment]
Yeah we made the decision to "squash" user permissions on the share, so it doesn't always match how permissions work natively on linux either. We've occasionally had to tweak our Dockerfiles so that things work for our devs who use linux on their laptops.

I'm not sure how much common code would be shared between OS X Dinghy and a hypothetical Windows version of Dinghy, it seems like much of the code would have to change. Perhaps there's some useful common abstractions that could be pulled out though.

**Comment by codekitchen** [comment]
I'm going to close this, as there's no plans to add Windows support to Dinghy itself, and Docker for Windows is probably a better option anyway.
