### ISSUE TITLE
Issue starting containers after so long

### ISSUE THREAD

**Issue by zacheryph** [codekitchen/dinghy#14]
After dinghy VM is running for so long I end up getting this error when i go to restart / start a container:

```
zephyr:% fig run worker rails c
Cannot start container 923c78ef01a6d12515e903ec6f018985a8dd12835e0e753dbe018017952ad2d5: setup mount namespace stat /Users/context/src/[redact]: permission denied
```

dinghy up ; fig up ; do stuff, it works fine, restart containers, start new containers, works fine.  After so long it stops working.  I cannot pinpoint a specific time / event thats happening that causes this though.  killing containers, restarting dinghy, bringing containers back up and everything works fine again.

**Comment by codekitchen** [comment]
This should be fixed in dinghy 2.2.1, which was released yesterday. There was a DHCP issue causing the VM IP address to change, which breaks the NFS mount. Are you on an older version? If so, follow the instructions @ https://github.com/codekitchen/dinghy#upgrading and let me know if you continue to see the issue. Thanks.
