### ISSUE TITLE
Should `dinghy up` really perform a restart?

### ISSUE THREAD

**Issue by fgrehm** [codekitchen/dinghy#153]
I'm a huge fan of https://github.com/jamesob/desk and I'm willing to start adding `dinghy up`s to my projects' `Deskfile`s but the fact that `dinghy up` restarts the VM in case it is already running will give me a bit of trouble as it might interfere with containers that are possibly running for other projects.

I could not spot a discussion about this and the [commit that introduced it](https://github.com/codekitchen/dinghy/commit/9c2cbe27cdfd56d529e8daef0b640524b0ebe8c5) does not give me a lot of context around the change :cry: 

Is there a reason behind this behavior? Would you be willing to just "no-op" in case the machine is already up?

Cheers!

**Comment by codekitchen** [comment]
Yeah I'm :+1: on that, I think the restart was a misguided attempt to preserve the old behavior from the Vagrant days

**Comment by KamilKopaczyk** [comment]
Personally i find that command name a little bit misleading.
Sometimes when i'm not sure when dinghy is running i would rather do _dinghy up_ and get a message that nothing was done, because it's already running. Instead i'm getting ```ha-ha! dinghy actually was up, but now you have to wait for a restart``` :)
If i would like to do a restart, i would run _dinghy restart_.

I know that i can run _dinghy status_ and then _dinghy up_, but that's 2 commands instead of 1.

**Comment by codekitchen** [comment]
Done. Note that to match `docker-machine start`, it exits with a non-zero status code if the machine is already running.

**Comment by fgrehm** [comment]
Thanks a lot!
