### ISSUE TITLE
Allow NFS config preference

### ISSUE THREAD

**Issue by corbinu** [codekitchen/dinghy#161]
I am running into issue 

https://github.com/codekitchen/dinghy/issues/31

I understand why this was a "won't fix" but I was wondering if there could be a preference for the NFS config.

As far as I can tell it is currently 
```
#{host_mount_dir}" #{machine.vm_ip}(rw,all_squash,anonuid=#{Process.uid},anongid=#{Process.gid})
```

I was hoping for an option to allow me to specify a different NFS config in 
HOME/.dinghy/preferences.yml

Or maybe just an option to allow people to chose `no_root_squash` if they wanted.

Thanks

**Comment by codekitchen** [comment]
Hey @corbinu, we originally had the dinghy NFS volume configured to not squash the user, but it caused even more problems for dinghy's intended use cases, which is why we switched over to squashing. I've resisted making it a configurable option for two reasons: fragmentation and learning curve.

By that I mean, it'd end up being a huge pain if some projects were set up to work with dinghy with squashing, and some were set up to work without squashing. You'd either have to juggle multiple VMs or change the option and restart dinghy constantly, and you wouldn't be able to easily run both projects at once. And since they're both imperfect solutions, we'd need a lot of documentation around how to choose which option to use. I'd like to avoid that.

That doesn't mean I'm happy with the current state of things, I'm always on the lookout for a better solution that has the pros of both approaches.

**Comment by corbinu** [comment]
@codekitchen Alright well what about an option to disable NFS entirely and just fallback to Virtualbox sharing like boot2docker. Honestly for the moment I have had to stop using dinghy because of this (makes the npm cache on the host unusable in dinghy). I would like to get back at least the virtual host names as I can live with the degraded FS performance.

**Comment by codekitchen** [comment]
Hm, not exactly what you're looking for, but we're actually in the process of pulling the dns+proxy functionality out into a separate more generic project, as our devs who run linux would like to use it as well.

Have you looked into storing the npm cache on a docker named volume, rather than on your host machine? I believe that's what our node teams here do.

**Comment by corbinu** [comment]
That would be very cool to have on our linux boxes as well! That could work will look into it. Thanks a bunch for all your hard work!
