### ISSUE TITLE
Space disk into the VM

### ISSUE THREAD

**Issue by yograterol** [codekitchen/dinghy#171]
Hi,

We are using Dinghy, and we have a problem with container that has volume in /var/lib, but with a large databases or files the disk is full because in a standard installation the root / has only 2.4 G. Can we increase the root spaces or when we create the VM set a fixed size for the root or another mount?

We have a team with members that use Linux and another OS X.

Regards

**Comment by codekitchen** [comment]
@yograterol do you mean that you are mounting a dir under `/var/lib` as a container volume? That sounds like a situation where you should be using a docker volume instead. Doubly so with docker-machine / boot2docker, because the root partition is in-memory and doesn't persist across VM reboots.

If you _do_ want to pursue it, the VM is created by docker-machine, so you'll likely need to file an issue with that project if you'd like to see a way to increase the root partition size. I'd suggest changing your setup though.

**Comment by codekitchen** [comment]
Closing this as there's nothing actionable that needs to be changed in dinghy.
