### ISSUE TITLE
DNS (SRV records) lookups fail inside docker container

### ISSUE THREAD

**Issue by bkad** [codekitchen/dinghy#172]
This issue is pretty much identical to https://github.com/boot2docker/boot2docker/issues/627.
Any SRV record lookups I made inside the container failed. I've fixed it by running:

```
VBoxManage modifyvm "dinghy" --natdnshostresolver1 off
VBoxManage modifyvm "dinghy" --natdnsproxy1 on
```

I'd like to know if dinghy can switch to the VirtualBox DNS proxy instead of using the host-based resolver.

**Comment by codekitchen** [comment]
Hm, we ran into issues with very slow DNS queries when trying to use `natdnsproxy1` instead of `natdnshostresolver1`. At the time I found https://www.virtualbox.org/ticket/11663, which looks similar but not quite the same issue. That was about 18 months ago though, so it's quite possible that the issue has been fixed since then. I'll experiment with this again.

**Comment by codekitchen** [comment]
I remember the bigger issue now. Using `natdnsproxy1` breaks the ability to resolve `*.docker` from within the VM, which is commonly used. Fixing that might require setting up a DNS proxy of our own, rather than just relying on the OS X `/etc/resolver` functionality.

**Comment by bkad** [comment]
Good to know, thanks for looking into it!

**Comment by codekitchen** [comment]
I've added this to the Dinghy FAQ, I'm going to close the issue as there isn't a known fix that'll solve all virtualbox DNS problems.
