### ISSUE TITLE
Enabling both http and https for a container

### ISSUE THREAD

**Issue by trakos** [codekitchen/dinghy#176]
After adding a certificate for container in `HOME/.dinghy/certs`, regular port 80 serves only a redirect to https. I would like to enable both http and https.

I've noticed that proxy hardcodes reditect in nginx.tmpl: https://github.com/codekitchen/dinghy-http-proxy/blob/master/nginx.tmpl#L67-L72 . Maybe env variable like VIRTUAL_NO_HTTPS_REDIRECT could be added that would prevent this and would insert same config for http as when certificate does not exists?

**Comment by ttrakos** [comment]
Looks like this feature was added to nginx-proxy today: https://github.com/jwilder/nginx-proxy/pull/298

**Comment by codekitchen** [comment]
Cool, that sounds reasonable to me. https://github.com/codekitchen/dinghy-http-proxy is a fork now, because of the more invasive changes we had to make for it to work seamlessly with docker-compose v2 files for local dev. If somebody wants to rebase that upstream PR against it I'd be happy to merge it.
