### ISSUE TITLE
FSevents fails with Permission Denied error

### ISSUE THREAD

**Issue by MrMMorris** [codekitchen/dinghy#186]
Getting a new developer going with dinghy and `dinghy up` says FSevents didn't start. Error below:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/bigdecimal-1.2.5 (Errno::EACCES)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
```

Tried a couple things:
1. noticed bigdecimal 1.2.0 and 1.2.5 were installed. I only have 1.2.0 so I got them to uninstall 1.2.5 but that didn't help
2. delete and recreate dinghy vm
3. `gem update --system`

FSevents still won't start. Any ideas?

**Comment by codekitchen** [comment]
Was there any more stacktrace? This looks like it's happening during installation of the `fsevents_to_vm` gem, but that runs with sudo so I'm not sure how you'd get this error. It'll essentially run:

```
sudo /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/gem install --no-rdoc --no-ri -n /usr/local/bin fsevents_to_vm -v "~> 1.1.2"
```

If it's happening when running the gem, `/usr/local/bin/fsevents_to_vm`, rather than during the install, that'd explain the permission error, but I don't know why it'd be trying to create this directory at that point.

**Comment by MrMMorris** [comment]
that's all that was in the log file. Do the gems get installed on `dinghy up`?

**Comment by codekitchen** [comment]
The gems do get installed on `dinghy up`, but that happens synchronously. The log file isn't created until it forks to run the background fsevents daemon process, so that implies the `gem install` already finished successfully.

I can't think of any reason it'd be trying to create this directory on startup, it seems like it's got to be something ruby or rubygems is trying to do. Does it happen if you run the gem directly with `/usr/local/bin/fsevents_to_vm help` ?

**Comment by MrMMorris** [comment]
`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/ffi-1.9.6 (Errno::EACCES)`

**Comment by codekitchen** [comment]
Geez, that almost looks like it's trying to compile the ruby C extensions at runtime, rather than on gem install, but I've never heard of rubygems doing that. There must be something unusual about this machine's ruby configuration, but I'm not sure what yet.

**Comment by codekitchen** [comment]
Perhaps if you ran `sudo /usr/local/bin/fsevents_to_vm` one time, so that it can do whatever it's trying to do? And then after that it may not need sudo anymore. That's total conjecture though.

**Comment by MrMMorris** [comment]
so we ran into a libxml2 dependency issue when running `fsevents_to_vm` which means down the ruby troubleshooting dependency hole. 

We have instead given up and gone with the scorched earth approach of uninstalling everything `dinghy` related, `rm -rf /Library/Ruby/Gems/2.0.0` + `gem update --system`, and then start the install from scratch.

As it seems like this isn't really a `dinghy` issue anyways, I am going to close this. Thanks again for the quick response as always.

**Comment by codekitchen** [comment]
Man. Whose bright idea was it to write this in Ruby.
