### ISSUE TITLE
Make the underlying host machine reachable from within a container.

### ISSUE THREAD

**Issue by hsyed** [codekitchen/dinghy#187]
Would it be possible to make the physical machine running the virtualised docker host reachable from within containers. My use case would be to be able to have my nginx containers reverse proxy to a java app running under an IDE in OSX.

**Comment by codekitchen** [comment]
This already works today, you'll just need to point the docker container at the IP address of your host machine. For instance:

```bash
# in terminal A
$ nc -l 192.168.64.1 5757

# in terminal B
$ docker run --rm -it busybox
echo hello | nc 192.168.64.1 5757

# terminal A prints "hello"
```

**Comment by hsyed** [comment]
I tried that and it works as expected, being able to route traffic to the machine is one part of the solution. The second part is being able to get the IP of the host machine. Would it be possible to have dinghy maintain a predifined hostname in it's DNS server that always resolves to the IP of the host machine ?

**Comment by codekitchen** [comment]
Yeah that seems reasonable.

On Jun 4, 2016, at 11:23, Hassan Syed <notifications@github.com> wrote:

I tried that and it works as expected, being able to route traffic to the
machine is one part of the solution. The second part is being able to get
the IP of the host machine. Would it be possible to have dinghy maintain a
predifined hostname in it's DNS server that always resolves to the IP of
the host machine ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/codekitchen/dinghy/issues/187#issuecomment-223767532>,
or mute the thread
<https://github.com/notifications/unsubscribe/AADLzFxpRCpTIFbXQR7TsbZ6hYc6g5Mqks5qIbSqgaJpZM4IuBMX>
.

**Comment by codekitchen** [comment]
I just merged https://github.com/codekitchen/dinghy/commit/a35f655f5e50c7966e34ef86ab637a2d63939630 , dinghy HEAD now has a `hostmachine.docker` hostname pointing back to the host OS X machine.
