### ISSUE TITLE
preferences being ignored?

### ISSUE THREAD

**Issue by MrMMorris** [codekitchen/dinghy#188]
I have the following in `~/.dinghy/preferences.yml`:
```yaml
---
:preferences:
  :proxy_disabled: true
```

and yet, when dinghy starts, it downloads and starts the proxy container.

Any idea why the setting is being ignored?

**Comment by paschdan** [comment]
I guess it is that way since 4.4.0 where they moved DNS inside a container with the proxy... 

As I have the same preference not to use the proxy, because i want to use my own proxy we are forced to use dinghy version 4.3.2

With homebrew you can install it via

`brew unlink dinghy`

`brew install https://raw.githubusercontent.com/codekitchen/homebrew-dinghy/10079cc56f86c37b000e4cf28862e5e61ce47607/Formula/dinghy.rb`

If there is any better solution to use dinghy with dns and nfs but without the proxy, please let me know

**Comment by codekitchen** [comment]
Yeah I should change the container name, it's misleading now that it's used for DNS as well. No need to stay on the old version of Dinghy, though, if you set proxy_disabled then it'll skip exposing the HTTP proxy ports to the host: https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/http_proxy.rb#L90

So you can still have your own proxy listening on 80/443

**Comment by MrMMorris** [comment]
I didn't realize that DNS was in the proxy container now. Thanks for the info
