### ISSUE TITLE
Failed to start container: mkdir /Users: file exists

### ISSUE THREAD

**Issue by t11n** [codekitchen/dinghy#211]
Hi there,

We have a problem that containers do not get restarted when doing `dinghy up` and `dinghy down` from the mac machine. We use dinghy with VMWare Fusion. Containers have the option "restart unless-stopped" applied.

We have four containers running, that have volumes pointing to /Users assigned. The first one does restart, from the second we find this in docker.log:

`time="2016-09-30T07:28:17.670532357Z" level=error msg="Failed to start container 8a7b2f7bf56be16f011ac8bc1ce5e47888086b50ecd5f712e0fccd4f426d7a32: mkdir /Users: file exists"`

Neither does this happen, when restarting docker within boot2docker, nor when restarting the entire boot2docker image. In those cases containers restart just fine. However, `dinghy up` and `dinghy down` reproduce the issue reliably.

Any idea?

Thanks!

**Comment by codekitchen** [comment]
Because Dinghy is built as a layer on top of docker-machine, we don't have a lot of control over the startup process. Basically, we wait for docker-machine to do its thing, then we mount the NFS volume to `/Users/<you>`. But that means docker is already running before we get a chance to do the mount. Probably what's happening is your containers are trying to access that mount before it's available.

I think you're the first report I've seen of somebody using auto-restart containers with Dinghy, so I haven't seen this problem before, but it makes sense. I'm not sure there's a whole lot we can do, unfortunately -- you could modify your containers to wait until the mount is available, if that's worth the work to you.

**Comment by t11n** [comment]
Thanks, that is good information. Yes, I also think it makes sense to restart development containers on start of the system. I work at an ecommerce company that works with the same projects over years and it would be a nice thing to fire up dinghy and have the entire environment up and running instantly (With docker for mac, I even set it up so all containers are restarted right after boot; that was awesome, but the filesystem shares were just too slow as you all know).

Ok, I got your point and you are probably right. It is likely to be nginx that tries to access the volumes right after restart. Containers not accessing volumes on the host restart properly. Your explanation also explains why volumes are assigned correctly after restarting docker or even reboot the boot2docker vm: NFS shares are simply still around as dinghy did not restart. 

Hmm, after all this is not good news. Could you maybe point me to the file(s) that triggers the startup process so I can do a little bit of more investigation? The boot2docker image doesn't follow usual run levels as far as I can see. So I am a little bit lost there.

Maybe I can take the issue over to docker then, asking them why the containers have to die if a volume folder already exists.

Thanks a lot!

**Comment by codekitchen** [comment]
Startup happens in the `start_services` method: https://github.com/codekitchen/dinghy/blob/master/cli/cli.rb#L207

Have you considered managing all your services using compose and running `docker-compose up` after starting dinghy? That's the typical workflow that most projects are using.

There was talk a while back about adding "hooks" to Dinghy, so that you could drop a shell script somewhere in `~/.dinghy` and have that executed after `dinghy up` is done starting all the services. I think the person who proposed that ended up just switching to compose, though, so they never implemented it.

**Comment by t11n** [comment]
Ah I see, so you did not modify the boot2docker image, but dinghy ssh's into the machine after startup and mounts the devices. That makes it difficult indeed.

We use docker-compose with our projects, but we have several ones that are loosely coupled. Imagine two main projects, one of it is not dockerized, yet. The other has three containers which are managed by docker-compose. Then there is something like a single sign on service, that is used by both main projects. It clearly does not belong to one or the other. It is a service on its own, so it comes with its own docker-compose setup. Then there is another smaller project, that is a development sandbox for one of the main projects. Does not belong to the main project either, though we could have a debate about that. When the second main project gets dockerized, there will be even more containers. Hope you get me.

Anyway, there is a a whole service composition that should come up in the mornings and preferably I would not like to do any docker-compose up on a routine basis at all. Not to think of doing it three or even more times.

That hooks idea would come in handy for me. I now did something similar by setting up a shell script `dinghy-start`, which starts dinghy and after that restarts all known containers. This works and comes close to the previous setup I had with docker for mac. With that it was really like booting the mac and have the entire docker composition running right after login, without having to call anything on the console.

I know it is not a too important issue, but small things matter. I simply do not want to care about the containers coming up in the mornings. Well and as there are many small things, you have to consolidate those from time to time. This saves me some energy for the real work to do :-)

I would be happy, if somebody would pick up that hooks idea, but I guess I will have to live with the shell script for some time. That's ok.

Thanks for your support. You can close the issue, if you like.

Cheers!

**Comment by codekitchen** [comment]
Yeah I'm open to the hooks idea but the work will probably have to come from somebody else, since it's not something my company has a use case for. I'll close this then.

**Comment by t11n** [comment]
I would invest some time in it, if I only knew Ruby. My company does php and perl, so unfortunately no expertise in your area.

Anyway, we can use Dinghy. Good job!
