### ISSUE TITLE
Preferences file is ignored on macOS Sierra?

### ISSUE THREAD

**Issue by mattlubner** [codekitchen/dinghy#213]
I have the following preferences saved in `~/.dinghy/preferences.yml` but for some reason the dinghy proxy is still being started. Have I done something wrong?

```yml
---
:preferences:
  :proxy_disabled: true
  :fsevents_disabled: false
  :create:
    provider: virtualbox
```

Any help would be greatly appreciated!

*System Info:*
- macOS Sierra Version 10.12 (16A323)
- Docker versions:
```sh
> dinghy version
Dinghy 4.4.1
> docker-machine version
docker-machine version 0.8.1, build 41b3b25
> docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
```

**Comment by codekitchen** [comment]
The proxy container also runs the DNS server, so the container gets started even if the proxy itself is disabled and not port-mapped to the host. I need to cut a new release, there's a change on master branch to modify the status output to be a little more clear https://github.com/codekitchen/dinghy/commit/3396e246adc77ecb4c196d812e99ac79eadc11e8

**Comment by codekitchen** [comment]
I've released Dinghy v4.4.2 which includes this clarification

**Comment by mattlubner** [comment]
I guess I'm still a little confused. Why does the DNS server need to be running at all, if the proxy is disabled? Is it possible to disable both?

**Comment by codekitchen** [comment]
Oh, I did that at user request, there's some people who run their own proxy on 80/443 or access their containers directly, but still want the convenience of using `*.docker` to reach the containers. There's no config option right now to disable DNS too, it's just never been necessary since it doesn't really hurt anything if you don't use it (unlike the HTTP proxy, which grabs ports 80 and 443 preventing other containers from using those). I'd be fine with getting that option added, though.

**Comment by mattlubner** [comment]
Aaah, gotcha, makes sense! Okay cool, just wanted to verify that I can safely stop + remove that container without causing any instability to the Dinghy setup! 😎
