### ISSUE TITLE
Using Dinghy in tandem with docker-osx-dev

### ISSUE THREAD

**Issue by glifchits** [codekitchen/dinghy#214]
Hey, I've been using Dinghy for docker dev for a while now and my experience has been great! Thanks for your great work.

I just found [docker-osx-dev](https://github.com/brikis98/docker-osx-dev) which is a nice script that syncs your host mounted Docker volumes using rsync. It is much faster than Dinghy, file changes are synced instantaneously. But when I use it with my Dinghy setup, all the files on my host Mac have the UID and GID from the `docker` user in the `dinghy` VM. 

I have more details in https://github.com/brikis98/docker-osx-dev/issues/196, which I filed since I thought the issue was related to the script. But it seems possible that Dinghy NFS mounting is the culprit here.

Can anyone confirm that the issue is indeed due to NFS mounting, and if so, is there anything we can do?

**Comment by codekitchen** [comment]
Thanks. It's unlikely you'll be able to get docker-osx-dev and dinghy working together, since they both have conflicting methods for doing host volume mounts. The one-way rsync method is faster, as you say, but we chose NFS for dinghy because two-way file syncing is important to our workflow. I don't know how you'd get both methods working together, since rsync to the VM would then trigger NFS writes back to the host in a circular manner.

But, I'm not sure why you need dinghy if you're also using docker-osx-dev. If it's because you like the HTTP proxy, note that is a separate project that can be used outside of dinghy: https://github.com/codekitchen/dinghy-http-proxy

Is there another use case here I'm missing?

**Comment by glifchits** [comment]
Thanks for this info @codekitchen. There's no special use case here, I only tried out `docker-osx-dev` since I thought it was a quick solution to speed up host mounted volume file synchronization. I understand now why Dinghy won't work for this!
