### ISSUE TITLE
unfs3 was moved to the boneyard

### ISSUE THREAD

**Issue by ryansch** [codekitchen/dinghy#219]
See: https://github.com/Homebrew/homebrew-core/pull/7667

We either need to get this reversed or add it to the dinghy tap.

**Comment by tierra** [comment]
As a workaround, you can just install unfs3 from boneyard explicitly, and continue with Dinghy install normally:

```
brew install homebrew/boneyard/unfs3
```

**Comment by ryansch** [comment]
That's exactly what I did. Not good for new users though.

**Comment by medinae** [comment]
👍

**Comment by codekitchen** [comment]
Bleh that's a pain. I've added ufs3 to the dinghy tap for now while I try to get this resolved with homebrew. Installation succeeds, though you'll see `Warning: Bottle installation failed: building from source.` and it'll build from source, because I'm not sure how to fix the bottle setup. Can somebody else confirm they can install without manually tapping from boneyard now?

**Comment by langsharpe** [comment]
Hi. I tried to upgrade dinghy today, and ran into a problem.
```
~> brew upgrade dinghy
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
codekitchen/dinghy/dinghy 4.4.2
Error: Formulae found in multiple taps:
 * codekitchen/dinghy/unfs3
 * homebrew/boneyard/unfs3

Please use the fully-qualified name e.g. codekitchen/dinghy/unfs3 to refer the formula.
```

Maybe adding unfs3 to your own tap has made this worse? I had run `brew update` beforehand. Let me know if you need anymore information.

**Comment by codekitchen** [comment]
Ah, I hadn't tried it with the boneyard tapped as well. I also didn't realize that I could give a fully-qualified name for a dependency, so I've modified the dinghy tap to remove its new copy of the unfs3 formula, and it references `homebrew/boneyard/unfs3` directly now.

In my testing, that results in auto-tapping the boneyard if you don't already have it tapped. That seems OK to me, especially since this should be a temporary solution.

**Comment by codekitchen** [comment]
I'm going to close this issue as the workaround seems to be working OK. Follow https://github.com/Homebrew/homebrew-core/pull/7825 if you're interested in the efforts to get unfs3 added back to homebrew-core.
