### ISSUE TITLE
Docker when on `dinghy create` after `dinghy destroy`

### ISSUE THREAD

**Issue by zwily** [codekitchen/dinghy#233]
I just did a `dinghy destroy` and `dinghy create`, and get this error:

```
zach-l:~ zach $ dinghy create
/usr/local/Cellar/dinghy/4.4.3/cli/dinghy.rb:98:in `version': Could not check docker --version, is it installed? (RuntimeError)
	from /usr/local/Cellar/dinghy/4.4.3/cli/dinghy.rb:78:in `block in version_check'
	from /usr/local/Cellar/dinghy/4.4.3/cli/dinghy.rb:77:in `each'
	from /usr/local/Cellar/dinghy/4.4.3/cli/dinghy.rb:77:in `version_check'
	from /usr/local/Cellar/dinghy/4.4.3/cli/dinghy.rb:43:in `run_checks'
	from /usr/local/bin/_dinghy_command:11:in `<main>'
zach-l:~ zach $ docker --version
could not read CA certificate "/Users/zach/.docker/machine/machines/dinghy/ca.pem": open /Users/zach/.docker/machine/machines/dinghy/ca.pem: no such file or directory
```

**Comment by zwily** [comment]
It looks like I have to clear out my `DOCKER_*` env variables in order to run `dinghy create`.

**Comment by codekitchen** [comment]
Looks like `docker --version` (tested with docker 1.13.0) now tries to the connect to the docker server, it didn't used to do that. I'm not sure why, since it still only prints out the client version, maybe it just happens for all commands now.

We'll have to modify Dinghy to unset the env vars before shelling out to run `docker --version`.
