### ISSUE TITLE
NFS issues caused by recent Docker change

### ISSUE THREAD

**Issue by seeruk** [codekitchen/dinghy#235]
It looks like [this commit](https://github.com/docker/docker/commit/72d8a77d522896ec73e07f49a1c1bcb44bbf3bbd) is causing some issues for us NFS users. I'm not entirely sure how we can get around it, but it may be possible with some NFS options. I can't really comment more on it than that.

The issue occurs when you're mounting a volume from the host, and the host-side doesn't exist. For example, if you have a directory you're going to mount a volume to, and you expect the Docker container to produce a bunch of files in there when it starts instead of starting with a bunch of files (e.g. first-time run of a container).

When this happens, here is the error:

```
$ docker-compose up
Starting <container_name>

ERROR: for <compose_name>  Cannot start service <compose_name>: error while creating mount source path '<host-side mount point>': <host-side mount point>: operation not permitted
ERROR: Encountered errors while bringing up the project.
```

If you then just run `$ docker-compose up` again straight away, it will work (as you can see from the above commit, it only tries to chown after making the folder, and only if it doesn't exist. So, on the second run it has already created it and continues fine from there.

Right now it's only a bit of a minor annoyance, but it would be great to see this issue resolved.

Here's some info about my environment:

```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   49bf474
 Built:
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ dinghy version
Dinghy 4.5.0
```

```
$ docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                                           NAMES
a963d0862e74        codekitchen/dinghy-http-proxy:2.5   "/app/docker-entry..."   15 minutes ago      Up 15 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 19322/tcp, 0.0.0.0:19322->19322/udp   dinghy_http_proxy
```

Running on OS X 10.11.6.

**Comment by codekitchen** [comment]
Hm yeah that's unfortunate but the change makes sense from their end. We haven't run into this yet because in all our docker-compose apps any host-mounted volumes are pre-created and committed to the git repos, you could do that as a workaround to avoid these errors on first startup.

This is related to the other chown/chmod issues that have come up in the past due to the way we're remapping the VM volume to your user on the host MacOS machine, see this FAQ entry: https://github.com/codekitchen/dinghy/blob/master/FAQ.md#im-running-into-file-permissions-issues-on-the-nfs-mounted-volumes

As outlined in the FAQ, I'm not aware of any easy solution -- we'd have to do something like modify the unfs3 daemon to ignore chown/chmod commands. I keep hoping that docker's user namespacing support will eventually solve the issue but it's still not in a state where it helps us here.

**Comment by SeerUK** [comment]
Yeah, I suppose that's a decent enough workaround for now in this case. I really hope Docker for Mac catches up with Docker Machine in terms of stability and performance soon. I tried Docker for Mac very recently but kept getting a bunch of issues with following logs crashing Docker Compose... strange.

To be honest though, if that modified unfs3 daemon could work, and it was pulled off well enough - that would be an amazing solution. I just have to worry what other problems it could then cause instead! That's the problem with this sort of thing I guess - as you said in the FAQ, there really is no one-size-fits-all solution without departing to Linux (or using a remote Linux development environment I guess).

**Comment by codekitchen** [comment]
I'm going to close this, as I'm not sure there's anything we can take action on here.
