### ISSUE TITLE
`dinghy start` overrides `:proxy_disabled` preferences

### ISSUE THREAD

**Issue by charlesfleche** [codekitchen/dinghy#261]
We are running dinghy with xhyve and deactivate the proxy to bind an nginx server directly to the port 80. Our `preferences.yml` looks like that:

``` yaml
---
:preferences:
  :proxy_disabled: true
  :fsevents_disabled: false
  :create:
    provider: xhyve
    memory: 1024
    cpus: 1
  :unfs_disabled: false
  :dns_disabled: false
```

However after a `dinghy up` the `proxy_disabled` setting is reset to `false`. So the first `dinghy up` will have the proxy turned off, but the second `dinghy up` will keep the proxy running, breaking our dev environment.

**Comment by codekitchen** [comment]
Hm yeah the logic got changed and is definitely wrong now. I've changed it back and pushed a new v4.6.1 release, so an update should get you fixed up.

Note that if you leave DNS enabled the http_proxy container will still be run, since it runs the DNS service too, it just won't bind to ports 80/443. I should probably rename the container or run two separate containers.
