### ISSUE TITLE
VM seems slow to respond to shared filesystem changes

### ISSUE THREAD

**Issue by SeanZicari** [codekitchen/dinghy#32]
I've got some python apps running, using gunicorn with the ``--reload`` option. I had lots of other issues w/ boot2docker, but the apps always reloaded almost immediately after a change. I'm finding the dinghy VM responds very slowly. I'm also not seeing my Flask assets being rebuilt at the expected times w/ dinghy. I'm wondering if this is to be expected, or maybe there are some settings I can tweak?

Thanks.

**Comment by codekitchen** [comment]
This is a known issue, the reason is that file shares over NFS don't support inotify filesystem events. There's an epic discussion over at https://github.com/codekitchen/dinghy/issues/9 , but the tl;dr is that you can try out my experimental solution as discussed at https://github.com/codekitchen/dinghy/issues/9#issuecomment-112856785 , I'd love to hear if it works well with gunicorn. I'll close this in favor of that existing issue.

**Comment by SeanZicari** [comment]
Thanks for that info! Quite a discussion, as you say. Now that I know this is what's going on, I've found another interim solution that works for now: sending a HUP signal to gunicorn from the host. Even though it's an extra step, at least I know the app is reloaded.

Thanks again for dinghy!
