### ISSUE TITLE
Prevent VM from "sleeping"

### ISSUE THREAD

**Issue by MrMMorris** [codekitchen/dinghy#61]
This may be a Virtualbox/Vagrant question, but do you know how to prevent the VM from being "saved" after some period of inactivity?

After not using it for a bit, I get `Cannot connect to the Docker daemon. Is 'docker -d' running on this host?` 

`$ dinghy status`
  `VM: saved`

So I try `dinghy up`, but then I get:

```
mount: mounting 192.168.42.1:/Users/mmorris on /Users/mmorris failed: Device or resource busy
/usr/local/Cellar/dinghy/3.0.4/cli/dinghy/vagrant.rb:40:in `ssh': Error executing command: sudo mount -t nfs 192.168.42.1:/Users/mmorris /Users/mmorris -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr (RuntimeError)
	from /usr/local/Cellar/dinghy/3.0.4/cli/dinghy/vagrant.rb:59:in `mount'
	from /usr/local/Cellar/dinghy/3.0.4/cli/cli.rb:35:in `up'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:5:in `<main>'
```

So I have to `dinghy halt` then `dinghy up`. This is a pain as I then have to rerun all my containers. I couldn't find any settings for this in Virtualbox and I don't think linux CLI has a "sleep" state.

Any ideas?

**Comment by codekitchen** [comment]
I haven't ever seen that with dinghy, and there's nothing running in the background that could even potentially run a VM shutdown. But it happens to me regularly with one of my other vagrant+virtualbox VMs. I've never dug into why. So yeah, it's likely a virtualbox question.

I did upgrade to virtualbox 5 last week, and haven't noticed it since then. Might be coincidence, but maybe try that if you aren't already on 5.x?

**Comment by MrMMorris** [comment]
I'll give that a try, thanks!
