### ISSUE TITLE
Issue upgrading to 4

### ISSUE THREAD

**Issue by joergd** [codekitchen/dinghy#65]
Hi,

I did a dinghy destroy before using brew to get the new version.

Then I want to do a 

    dinghy help create

and I get the following issue:

    >: dinghy help create
    dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
      Referenced from: /Users/joerg/.rvm/gems/ruby-2.2.1/gems/json-1.8.2/lib/json/ext/parser.bundle
      Expected in: flat namespace

    dyld: Symbol not found: _rb_str_new_static
      Referenced from: /Users/joerg/.rvm/gems/ruby-2.2.1/gems/json-1.8.2/lib/json/ext/parser.bundle
      Expected in: flat namespace

    Trace/BPT trap: 5

**Comment by codekitchen** [comment]
I just had a co-worker run into this as well. Dinghy uses the OS X system ruby, located at `/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby`, but something about his (and your) rvm setup is tricking ruby into loading the `json` gem from a different rvm-installed version of ruby.

It fails because ruby C extensions aren't compatible between versions. We need to find a workaround to force ruby to use the OS X system-installed version of the json gem even when rvm is messing with the execution environment.

In the meantime, I think that running `rvm use system` will switch rvm to using the system ruby as well, which should work around the issue.

**Comment by codekitchen** [comment]
We have a solution -- a wrapper bash script that unsets the GEM_HOME env vars ( https://github.com/codekitchen/dinghy/blob/master/bin/dinghy ). This is the same thing homebrew does to work around the problem ( https://github.com/Homebrew/homebrew/blob/master/bin/brew )

Released dinghy 4.0.1 with this workaround.

**Comment by joergd** [comment]
Hey that did it - thanks so much for solving it so quickly!
