### ISSUE TITLE
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/plist.rb:35:in `system!': Error with the FsEvents daemon during stopping (RuntimeError)

### ISSUE THREAD

**Issue by lukebarton** [codekitchen/dinghy#77]
```
$ dinghy up
Starting the dinghy VM...
Stopping NFS daemon, this will require sudo
Password:
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/lukebarton
Stopping the FsEvents daemon
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/plist.rb:35:in `system!': Error with the FsEvents daemon during stopping (RuntimeError)
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/plist.rb:16:in `halt'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/plist.rb:5:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/fsevents_to_vm.rb:17:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:184:in `start_services'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
        from /usr/local/bin/_dinghy_command:6:in `<main>'
```

**Comment by lukebarton** [comment]
Perhaps this is causing  #42 and #69 ?

**Comment by codekitchen** [comment]
It does seem related. This looks like a situation where the VM was stopped but the other dinghy services were running, which could happen if you reboot while dinghy is running, or otherwise halt the VM without running `dinghy halt`. That definitely doesn't always trigger this problem though, as a lot of us do that all the time too.

Specifically what failed is this shell command: `launchctl unload -w ~/Library/LaunchAgents/dinghy.fsevents_to_vm.plist`. We're just echoing all output to the terminal, so I'm surprised that it failed with no output. If you run that command manually in this situation, does it also fail with no output, but a non-zero exit code?

Using launchd for these dinghy services was always a Q&D hack to get dinghy functional ASAP, I'd love to swap it out in favor of managing our own daemons.

**Comment by lukebarton** [comment]
Unloading produces this system log entry:

```
26/09/2015 16:15:49.400 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.system) Caller not allowed to perform action: launchctl.24316, action = unbootstrap, code = 1: Operation not permitted, uid = 501, euid = 501, gid = 20, egid = 20, asid = 100005
```

**Comment by codekitchen** [comment]
I need to learn more about how launchd works internally. Do you use tmux? That's the same error as tmux users get, due to http://apple.stackexchange.com/questions/41412/using-tmux-and-pbpaste-pbcopy-and-launchctl , except they typically get it consistently rather than just sometimes.

**Comment by lukebarton** [comment]
Yes! I guess my inconsistent times were outside of tmux. I'll work around it.

**Comment by codekitchen** [comment]
Because of all the issues with using/abusing launchd the way we were, we've moved to our own daemon management code in the newest v4.1.0 release of dinghy. I'm going to close this, we'll handle any similar problems on the newest release as a new issue.

**Comment by lukebarton** [comment]
Thanks
