### ISSUE TITLE
Kitematic: IP: 192.168.99.100 is not in the cert's list: 192.168.99.101

### ISSUE THREAD

**Issue by entwu** [codekitchen/dinghy#96]
I love the speed that dinghy gives me. There is just one issue that bothers me - sometimes I use container logs a lot, Kitematic helpes me to do the job quickly. 
Is there any way to connect with Kitematic to the dinghy VM ?
This is similar issue: https://github.com/kitematic/kitematic/issues/519
After poking around with the issue I've ended up with Kitematic recreating/running default VM every time.

**Comment by codekitchen** [comment]
I haven't used Kitematic, so I don't know what would be involved in getting it to use the dinghy VM. It might be as easy as changing a config file somewhere, or maybe you could modify dinghy to allow you to specify a different docker-machine name -- and then just tell dinghy to use the Kitematic-created VM. I'm unlikely to tackle this myself since I don't use it, but I'd be totally into merging something that lets people do it.

**Comment by justafish** [comment]
I've got dinghy working with Kitematic by changing the VM's name to default. Pull Request to make that configurable here: #128

**Comment by Incisive** [comment]
+1 On this, I really could use the ability to change the machine name as we use a single docker-machine VM per project, so we have a few running sometimes and it would be helpful to be able to configure the name at creation :+1:

**Comment by codekitchen** [comment]
Kitematic should work with Dinghy now, thanks @justafish 

@Incisive you are correct, Dinghy is currently designed to just manage one VM. I'm not sure I understand the use case for using a different docker VM per project, but I'd be open to accepting a PR to enable that use case.
